<?xml version="1.0" encoding="utf-8"?><Database Name="Quan_Ly_Dai_Ly_Sach" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=TNNQ-SV\SQLEXPRESS;Initial Catalog=Quan_Ly_Dai_Ly_Sach;Integrated Security=True" SettingsObjectName="QuanLyDaiLySach_1453014_1453036.Properties.Settings" SettingsPropertyName="Quan_Ly_Dai_Ly_SachConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MaNhanVien" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTenNhanVien" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NoiSinh" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="ChungMinhThu" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Luong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LoaiNhanVien" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="CaLam" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="HinhThucLam" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>